---
latency-wait: 180
reason: True
show-failed-logs: True
keep-going: True
printshellcmds: True
rerun-incomplete: True
#restart-times: 1
notemp: True
# Cluster submission
jobname: "{rule}.{jobid}"              # Provide a custom name for the jobscript that is submitted to the cluster.
max-jobs-per-second: 10                #Maximal number of cluster/drmaa jobs per second, default is 10, fractions allowed.
max-status-checks-per-second: 10       #Maximal number of job status checks per second, default is 10
jobs: 50   
cluster: "sbatch --output=\"jobs/{rule}/slurm_%x_%j.out\" --error=\"jobs/{rule}/slurm_%x_%j.log\" --mem={resources.mem_mb} --time={resources.runtime} --cpus-per-task={threads}"
cluster-cancel: "scancel"

# Job resources
default-resources:
    - mem_mb=40000
    - runtime="02:00:00"
    - disk_mb=5000
set-threads:
    - STAR_2pass=10
    - STAR=10
    - mark_duplicates=2
    - split_n_cigar_reads=5
    - mutect=8
    - lofreq=8
    - scalpel=2
    - haplotypecaller=8
